[package]
name = "mc-status-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "time", "net", "io-util"] }
serde_json = "1.0.128"
log = "0.4.22"
byteorder = "1.5.0"
bytes = "1.7.1"